- hosts: master, worker
  become: true
  roles:
    - common_kubernetes

- hosts: master
  become: true
  roles:
    - kubernetes_master

- hosts: worker
  become: true
  roles:
    - kubernetes_worker

