- name: Add Helm repository for Prometheus
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update

- name: Create namespace 'monitoring'
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: monitoring

- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    name: monitoring
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    chart_ref: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    release_namespace: monitoring
    values: "{{ lookup('file', 'roles/kube-prometheus/files/grafana-values.yaml') | from_yaml }}"
