---
- name: Получение токена для присоединения к кластеру
  command: kubeadm token create --print-join-command
  register: join_command
  run_once: true
  delegate_to: "{{ groups['master'][0] }}"
  when: inventory_hostname == groups['worker'][0]

- name: Присоединение воркер-нод к кластеру
  command: "{{ hostvars[groups['worker'][0]].join_command.stdout }} --ignore-preflight-errors=all"